/*
 * This class was automatically generated with 
 * <a href="http://www.castor.org">Castor 1.0.2</a>, using an XML
 * Schema.
 * $Id$
 */

package nl.b3p.xml.wfs.v100;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import java.util.Collections;
import org.exolab.castor.xml.Marshaller;
import org.exolab.castor.xml.Unmarshaller;

/**
 * A GetFeature element contains one or more Query elements
 *  that describe a query operation on one feature type. In
 *  response to a GetFeature request, a Web Feature Service
 *  must be able to generate a GML2 response that validates
 *  using a schema generated by the DescribeFeatureType request.
 *  A Web Feature Service may support other possibly non-XML
 *  (and even binary) output formats as long as those formats
 *  are advertised in the capabilities document.
 *  
 * 
 * @version $Revision$ $Date$
 */
public class GetFeatureType implements java.io.Serializable {


      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field _version
     */
    private java.lang.String _version = "1.0.0";

    /**
     * Field _service
     */
    private java.lang.String _service = "WFS";

    /**
     * Field _handle
     */
    private java.lang.String _handle;

    /**
     * The outputFormat attribute is used to specify the output
     *  format that the Web Feature Service should generate in
     *  response to a GetFeature or GetFeatureWithLock element.
     *  The default value of GML2 indicates that the output is an
     *  XML document that conforms to the Geography Markup Language
     *  (GML) Implementation Specification V2.0.
     * 
     *  Other values may be used to specify other formats as long
     *  as those values are advertised in the capabilities
     * document.
     *  For example, the value WKB may be used to indicate that a 
     *  Well Known Binary format be used to encode the output.
     *  
     */
    private java.lang.String _outputFormat = "GML2";

    /**
     * The maxFeatures attribute is used to specify the maximum
     *  number of features that a GetFeature operation should
     *  generate (regardless of the actual number of query hits).
     *  
     */
    private int _maxFeatures;

    /**
     * keeps track of state for field: _maxFeatures
     */
    private boolean _has_maxFeatures;

    /**
     * The Query element is used to describe a single query.
     *  One or more Query elements can be specified inside a
     *  GetFeature element so that multiple queries can be 
     *  executed in one request. The output from the various
     *  queries are combined in a wfs:FeatureCollection element
     *  to form the response to the request.
     *  
     */
    private java.util.ArrayList _queryList;


      //----------------/
     //- Constructors -/
    //----------------/

    public GetFeatureType() 
     {
        super();
        setVersion("1.0.0");
        setService("WFS");
        setOutputFormat("GML2");
        _queryList = new java.util.ArrayList();
    } //-- nl.b3p.xml.wfs.v100.GetFeatureType()


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addQuery
     * 
     * 
     * 
     * @param vQuery
     */
    public void addQuery(nl.b3p.xml.wfs.v100.Query vQuery)
        throws java.lang.IndexOutOfBoundsException
    {
        _queryList.add(vQuery);
    } //-- void addQuery(nl.b3p.xml.wfs.v100.Query) 

    /**
     * Method addQuery
     * 
     * 
     * 
     * @param index
     * @param vQuery
     */
    public void addQuery(int index, nl.b3p.xml.wfs.v100.Query vQuery)
        throws java.lang.IndexOutOfBoundsException
    {
        _queryList.add(index, vQuery);
    } //-- void addQuery(int, nl.b3p.xml.wfs.v100.Query) 

    /**
     * Method clearQuery
     * 
     */
    public void clearQuery()
    {
        _queryList.clear();
    } //-- void clearQuery() 

    /**
     * Method deleteMaxFeatures
     * 
     */
    public void deleteMaxFeatures()
    {
        this._has_maxFeatures= false;
    } //-- void deleteMaxFeatures() 

    /**
     * Method enumerateQuery
     * 
     * 
     * 
     * @return Enumeration
     */
    public java.util.Enumeration enumerateQuery()
    {
        return Collections.enumeration(_queryList);
    } //-- java.util.Enumeration enumerateQuery() 

    /**
     * Returns the value of field 'handle'.
     * 
     * @return String
     * @return the value of field 'handle'.
     */
    public java.lang.String getHandle()
    {
        return this._handle;
    } //-- java.lang.String getHandle() 

    /**
     * Returns the value of field 'maxFeatures'. The field
     * 'maxFeatures' has the following description: The maxFeatures
     * attribute is used to specify the maximum
     *  number of features that a GetFeature operation should
     *  generate (regardless of the actual number of query hits).
     *  
     * 
     * @return int
     * @return the value of field 'maxFeatures'.
     */
    public int getMaxFeatures()
    {
        return this._maxFeatures;
    } //-- int getMaxFeatures() 

    /**
     * Returns the value of field 'outputFormat'. The field
     * 'outputFormat' has the following description: The
     * outputFormat attribute is used to specify the output
     *  format that the Web Feature Service should generate in
     *  response to a GetFeature or GetFeatureWithLock element.
     *  The default value of GML2 indicates that the output is an
     *  XML document that conforms to the Geography Markup Language
     *  (GML) Implementation Specification V2.0.
     * 
     *  Other values may be used to specify other formats as long
     *  as those values are advertised in the capabilities
     * document.
     *  For example, the value WKB may be used to indicate that a 
     *  Well Known Binary format be used to encode the output.
     *  
     * 
     * @return String
     * @return the value of field 'outputFormat'.
     */
    public java.lang.String getOutputFormat()
    {
        return this._outputFormat;
    } //-- java.lang.String getOutputFormat() 

    /**
     * Method getQuery
     * 
     * 
     * 
     * @param index
     * @return Query
     */
    public nl.b3p.xml.wfs.v100.Query getQuery(int index)
        throws java.lang.IndexOutOfBoundsException
    {
        //-- check bounds for index
        if ((index < 0) || (index >= _queryList.size())) {
            throw new IndexOutOfBoundsException();
        }
        
        return (nl.b3p.xml.wfs.v100.Query) _queryList.get(index);
    } //-- nl.b3p.xml.wfs.v100.Query getQuery(int) 

    /**
     * Method getQuery
     * 
     * 
     * 
     * @return Query
     */
    public nl.b3p.xml.wfs.v100.Query[] getQuery()
    {
        int size = _queryList.size();
        nl.b3p.xml.wfs.v100.Query[] mArray = new nl.b3p.xml.wfs.v100.Query[size];
        for (int index = 0; index < size; index++) {
            mArray[index] = (nl.b3p.xml.wfs.v100.Query) _queryList.get(index);
        }
        return mArray;
    } //-- nl.b3p.xml.wfs.v100.Query[] getQuery() 

    /**
     * Method getQueryCount
     * 
     * 
     * 
     * @return int
     */
    public int getQueryCount()
    {
        return _queryList.size();
    } //-- int getQueryCount() 

    /**
     * Returns the value of field 'service'.
     * 
     * @return String
     * @return the value of field 'service'.
     */
    public java.lang.String getService()
    {
        return this._service;
    } //-- java.lang.String getService() 

    /**
     * Returns the value of field 'version'.
     * 
     * @return String
     * @return the value of field 'version'.
     */
    public java.lang.String getVersion()
    {
        return this._version;
    } //-- java.lang.String getVersion() 

    /**
     * Method hasMaxFeatures
     * 
     * 
     * 
     * @return boolean
     */
    public boolean hasMaxFeatures()
    {
        return this._has_maxFeatures;
    } //-- boolean hasMaxFeatures() 

    /**
     * Method isValid
     * 
     * 
     * 
     * @return boolean
     */
    public boolean isValid()
    {
        try {
            validate();
        }
        catch (org.exolab.castor.xml.ValidationException vex) {
            return false;
        }
        return true;
    } //-- boolean isValid() 

    /**
     * Method marshal
     * 
     * 
     * 
     * @param out
     */
    public void marshal(java.io.Writer out)
        throws org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        
        Marshaller.marshal(this, out);
    } //-- void marshal(java.io.Writer) 

    /**
     * Method marshal
     * 
     * 
     * 
     * @param handler
     */
    public void marshal(org.xml.sax.ContentHandler handler)
        throws java.io.IOException, org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        
        Marshaller.marshal(this, handler);
    } //-- void marshal(org.xml.sax.ContentHandler) 

    /**
     * Method removeQuery
     * 
     * 
     * 
     * @param vQuery
     * @return boolean
     */
    public boolean removeQuery(nl.b3p.xml.wfs.v100.Query vQuery)
    {
        boolean removed = _queryList.remove(vQuery);
        return removed;
    } //-- boolean removeQuery(nl.b3p.xml.wfs.v100.Query) 

    /**
     * Sets the value of field 'handle'.
     * 
     * @param handle the value of field 'handle'.
     */
    public void setHandle(java.lang.String handle)
    {
        this._handle = handle;
    } //-- void setHandle(java.lang.String) 

    /**
     * Sets the value of field 'maxFeatures'. The field
     * 'maxFeatures' has the following description: The maxFeatures
     * attribute is used to specify the maximum
     *  number of features that a GetFeature operation should
     *  generate (regardless of the actual number of query hits).
     *  
     * 
     * @param maxFeatures the value of field 'maxFeatures'.
     */
    public void setMaxFeatures(int maxFeatures)
    {
        this._maxFeatures = maxFeatures;
        this._has_maxFeatures = true;
    } //-- void setMaxFeatures(int) 

    /**
     * Sets the value of field 'outputFormat'. The field
     * 'outputFormat' has the following description: The
     * outputFormat attribute is used to specify the output
     *  format that the Web Feature Service should generate in
     *  response to a GetFeature or GetFeatureWithLock element.
     *  The default value of GML2 indicates that the output is an
     *  XML document that conforms to the Geography Markup Language
     *  (GML) Implementation Specification V2.0.
     * 
     *  Other values may be used to specify other formats as long
     *  as those values are advertised in the capabilities
     * document.
     *  For example, the value WKB may be used to indicate that a 
     *  Well Known Binary format be used to encode the output.
     *  
     * 
     * @param outputFormat the value of field 'outputFormat'.
     */
    public void setOutputFormat(java.lang.String outputFormat)
    {
        this._outputFormat = outputFormat;
    } //-- void setOutputFormat(java.lang.String) 

    /**
     * Method setQuery
     * 
     * 
     * 
     * @param index
     * @param vQuery
     */
    public void setQuery(int index, nl.b3p.xml.wfs.v100.Query vQuery)
        throws java.lang.IndexOutOfBoundsException
    {
        //-- check bounds for index
        if ((index < 0) || (index >= _queryList.size())) {
            throw new IndexOutOfBoundsException();
        }
        _queryList.set(index, vQuery);
    } //-- void setQuery(int, nl.b3p.xml.wfs.v100.Query) 

    /**
     * Method setQuery
     * 
     * 
     * 
     * @param queryArray
     */
    public void setQuery(nl.b3p.xml.wfs.v100.Query[] queryArray)
    {
        //-- copy array
        _queryList.clear();
        for (int i = 0; i < queryArray.length; i++) {
            _queryList.add(queryArray[i]);
        }
    } //-- void setQuery(nl.b3p.xml.wfs.v100.Query) 

    /**
     * Sets the value of field 'service'.
     * 
     * @param service the value of field 'service'.
     */
    public void setService(java.lang.String service)
    {
        this._service = service;
    } //-- void setService(java.lang.String) 

    /**
     * Sets the value of field 'version'.
     * 
     * @param version the value of field 'version'.
     */
    public void setVersion(java.lang.String version)
    {
        this._version = version;
    } //-- void setVersion(java.lang.String) 

    /**
     * Method unmarshal
     * 
     * 
     * 
     * @param reader
     * @return GetFeatureType
     */
    public static nl.b3p.xml.wfs.v100.GetFeatureType unmarshal(java.io.Reader reader)
        throws org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        return (nl.b3p.xml.wfs.v100.GetFeatureType) Unmarshaller.unmarshal(nl.b3p.xml.wfs.v100.GetFeatureType.class, reader);
    } //-- nl.b3p.xml.wfs.v100.GetFeatureType unmarshal(java.io.Reader) 

    /**
     * Method validate
     * 
     */
    public void validate()
        throws org.exolab.castor.xml.ValidationException
    {
        org.exolab.castor.xml.Validator validator = new org.exolab.castor.xml.Validator();
        validator.validate(this);
    } //-- void validate() 

}
