/*
 * This class was automatically generated with 
 * <a href="http://www.castor.org">Castor 1.0.2</a>, using an XML
 * Schema.
 * $Id$
 */

package nl.b3p.xml.wfs.v110;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import java.util.Collections;
import org.exolab.castor.xml.Marshaller;
import org.exolab.castor.xml.Unmarshaller;

/**
 * Class InsertedFeatureType.
 * 
 * @version $Revision$ $Date$
 */
public class InsertedFeatureType implements java.io.Serializable {


      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * If the insert element that generated this feature 
     *  had a value for the "handle" attribute then a WFS
     *  may report it using this attribute to correlate
     *  the feature created with the action that created it.
     *  
     */
    private java.lang.String _handle;

    /**
     * This is the feature identifier for the newly created
     *  feature. The feature identifier may be generated by
     *  the WFS or provided by the client (depending on the 
     *  value of the idgen attribute). In all cases of idgen
     *  values, the feature id must be reported here.
     *  
     */
    private java.util.ArrayList _featureIdList;


      //----------------/
     //- Constructors -/
    //----------------/

    public InsertedFeatureType() 
     {
        super();
        _featureIdList = new java.util.ArrayList();
    } //-- nl.b3p.xml.wfs.v110.InsertedFeatureType()


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addFeatureId
     * 
     * 
     * 
     * @param vFeatureId
     */
    public void addFeatureId(nl.b3p.xml.ogc.v110.FeatureId vFeatureId)
        throws java.lang.IndexOutOfBoundsException
    {
        _featureIdList.add(vFeatureId);
    } //-- void addFeatureId(nl.b3p.xml.ogc.v110.FeatureId) 

    /**
     * Method addFeatureId
     * 
     * 
     * 
     * @param index
     * @param vFeatureId
     */
    public void addFeatureId(int index, nl.b3p.xml.ogc.v110.FeatureId vFeatureId)
        throws java.lang.IndexOutOfBoundsException
    {
        _featureIdList.add(index, vFeatureId);
    } //-- void addFeatureId(int, nl.b3p.xml.ogc.v110.FeatureId) 

    /**
     * Method clearFeatureId
     * 
     */
    public void clearFeatureId()
    {
        _featureIdList.clear();
    } //-- void clearFeatureId() 

    /**
     * Method enumerateFeatureId
     * 
     * 
     * 
     * @return Enumeration
     */
    public java.util.Enumeration enumerateFeatureId()
    {
        return Collections.enumeration(_featureIdList);
    } //-- java.util.Enumeration enumerateFeatureId() 

    /**
     * Method getFeatureId
     * 
     * 
     * 
     * @param index
     * @return FeatureId
     */
    public nl.b3p.xml.ogc.v110.FeatureId getFeatureId(int index)
        throws java.lang.IndexOutOfBoundsException
    {
        //-- check bounds for index
        if ((index < 0) || (index >= _featureIdList.size())) {
            throw new IndexOutOfBoundsException();
        }
        
        return (nl.b3p.xml.ogc.v110.FeatureId) _featureIdList.get(index);
    } //-- nl.b3p.xml.ogc.v110.FeatureId getFeatureId(int) 

    /**
     * Method getFeatureId
     * 
     * 
     * 
     * @return FeatureId
     */
    public nl.b3p.xml.ogc.v110.FeatureId[] getFeatureId()
    {
        int size = _featureIdList.size();
        nl.b3p.xml.ogc.v110.FeatureId[] mArray = new nl.b3p.xml.ogc.v110.FeatureId[size];
        for (int index = 0; index < size; index++) {
            mArray[index] = (nl.b3p.xml.ogc.v110.FeatureId) _featureIdList.get(index);
        }
        return mArray;
    } //-- nl.b3p.xml.ogc.v110.FeatureId[] getFeatureId() 

    /**
     * Method getFeatureIdCount
     * 
     * 
     * 
     * @return int
     */
    public int getFeatureIdCount()
    {
        return _featureIdList.size();
    } //-- int getFeatureIdCount() 

    /**
     * Returns the value of field 'handle'. The field 'handle' has
     * the following description: If the insert element that
     * generated this feature 
     *  had a value for the "handle" attribute then a WFS
     *  may report it using this attribute to correlate
     *  the feature created with the action that created it.
     *  
     * 
     * @return String
     * @return the value of field 'handle'.
     */
    public java.lang.String getHandle()
    {
        return this._handle;
    } //-- java.lang.String getHandle() 

    /**
     * Method isValid
     * 
     * 
     * 
     * @return boolean
     */
    public boolean isValid()
    {
        try {
            validate();
        }
        catch (org.exolab.castor.xml.ValidationException vex) {
            return false;
        }
        return true;
    } //-- boolean isValid() 

    /**
     * Method marshal
     * 
     * 
     * 
     * @param out
     */
    public void marshal(java.io.Writer out)
        throws org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        
        Marshaller.marshal(this, out);
    } //-- void marshal(java.io.Writer) 

    /**
     * Method marshal
     * 
     * 
     * 
     * @param handler
     */
    public void marshal(org.xml.sax.ContentHandler handler)
        throws java.io.IOException, org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        
        Marshaller.marshal(this, handler);
    } //-- void marshal(org.xml.sax.ContentHandler) 

    /**
     * Method removeFeatureId
     * 
     * 
     * 
     * @param vFeatureId
     * @return boolean
     */
    public boolean removeFeatureId(nl.b3p.xml.ogc.v110.FeatureId vFeatureId)
    {
        boolean removed = _featureIdList.remove(vFeatureId);
        return removed;
    } //-- boolean removeFeatureId(nl.b3p.xml.ogc.v110.FeatureId) 

    /**
     * Method setFeatureId
     * 
     * 
     * 
     * @param index
     * @param vFeatureId
     */
    public void setFeatureId(int index, nl.b3p.xml.ogc.v110.FeatureId vFeatureId)
        throws java.lang.IndexOutOfBoundsException
    {
        //-- check bounds for index
        if ((index < 0) || (index >= _featureIdList.size())) {
            throw new IndexOutOfBoundsException();
        }
        _featureIdList.set(index, vFeatureId);
    } //-- void setFeatureId(int, nl.b3p.xml.ogc.v110.FeatureId) 

    /**
     * Method setFeatureId
     * 
     * 
     * 
     * @param featureIdArray
     */
    public void setFeatureId(nl.b3p.xml.ogc.v110.FeatureId[] featureIdArray)
    {
        //-- copy array
        _featureIdList.clear();
        for (int i = 0; i < featureIdArray.length; i++) {
            _featureIdList.add(featureIdArray[i]);
        }
    } //-- void setFeatureId(nl.b3p.xml.ogc.v110.FeatureId) 

    /**
     * Sets the value of field 'handle'. The field 'handle' has the
     * following description: If the insert element that generated
     * this feature 
     *  had a value for the "handle" attribute then a WFS
     *  may report it using this attribute to correlate
     *  the feature created with the action that created it.
     *  
     * 
     * @param handle the value of field 'handle'.
     */
    public void setHandle(java.lang.String handle)
    {
        this._handle = handle;
    } //-- void setHandle(java.lang.String) 

    /**
     * Method unmarshal
     * 
     * 
     * 
     * @param reader
     * @return InsertedFeatureType
     */
    public static nl.b3p.xml.wfs.v110.InsertedFeatureType unmarshal(java.io.Reader reader)
        throws org.exolab.castor.xml.MarshalException, org.exolab.castor.xml.ValidationException
    {
        return (nl.b3p.xml.wfs.v110.InsertedFeatureType) Unmarshaller.unmarshal(nl.b3p.xml.wfs.v110.InsertedFeatureType.class, reader);
    } //-- nl.b3p.xml.wfs.v110.InsertedFeatureType unmarshal(java.io.Reader) 

    /**
     * Method validate
     * 
     */
    public void validate()
        throws org.exolab.castor.xml.ValidationException
    {
        org.exolab.castor.xml.Validator validator = new org.exolab.castor.xml.Validator();
        validator.validate(this);
    } //-- void validate() 

}
